const types = {
  createNFT: {
    SET_NAME: "CREATE_NFT_SET_NAME",
    SET_SYMBOL: "CREATE_NFT_SET_SYMBOL",
    SET_URI: "CREATE_NFT_SET_URI",
    SET_CONTRACT_ADDRESS: "CREATE_NFT_SET_CONTRACT_ADDRESS",
    CREATE_NFT_SUCCESS: "CREATE_NFT_SUCCESS",
    CREATE_NFT_FAIL: "CREATE_NFT_FAIL",
    CREATE_NFT_REQUEST: "CREATE_NFT_REQUEST",
  },
  token: {
    SET_NAME: "TOKEN_SET_NAME",
    SET_SYMBOL: "TOKEN_SET_SYMBOL",
    SET_CONTRACT_ADDRESS: "TOKEN_SET_CONTRACT_ADDRESS",
    SET_CURRENT_SUPPLY: "TOKEN_SET_CURRENT_SUPPLY"
  },
  collateralAndPrice: {
    SET_COLLATERAL: "COLLATERAL_AND_PRICE_SET_COLLATERAL",
    SET_PRICE: "COLLATERAL_AND_PRICE_SET_PRICE",
    SET_MAX_SUPPLY: "COLLATERAL_AND_PRICE_SET_SUPPLY"
  },
  curve: {
    SET_CURVE: "CURVE_SET_CURVE",
  },
  provider: {
    SET_PROVIDER: "SET_PROVIDER",
    SET_CHAIN_ID: "SET_CHAIN_ID"
  },
  SetWalletAddress: {
    SET_WALLET_ADDRESS_REQUEST: "SET_WALLET_ADDRESS_REQUEST",
    SET_WALLET_ADDRESS_SUCCESS: "SET_WALLET_ADDRESS_SUCCESS",
    SET_WALLET_ADDRESS_FAIL: "SET_WALLET_ADDRESS_FAIL",
    SET_WALLET_ADDRESS_PENDING: "SET_WALLET_ADDRESS_PENDING",
  },
  SetWalletConnected: {
    SET_WALLET_CONNECTED_REQUEST: "SET_WALLET_CONNECTED_REQUEST",
    SET_WALLET_CONNECTED_SUCCESS: "SET_WALLET_CONNECTED_SUCCESS",
    SET_WALLET_CONNECTED_FAIL: "SET_WALLET_CONNECTED_FAIL",
    SET_WALLET_CONNECTED_PENDING: "SET_WALLET_CONNECTED_PENDING",
  },
  SetProvider: {
    SET_PROVIDER_REQUEST: "SET_PROVIDER_REQUEST",
    SET_PROVIDER_SUCCESS: "SET_PROVIDER_SUCCESS",
    SET_PROVIDER_FAIL: "SET_PROVIDER_FAIL",
    SET_PROVIDER_PENDING: "SET_PROVIDER_PENDING",
  },
  createMarket: {
    CREATE_MARKET_SUCCESS: "CREATE_MARKET_SUCCESS",
    CREATE_MARKET_FAIL: "CREATE_MARKET_FAIL",
    CREATE_MARKET_REQUEST: "CREATE_MARKET_REQUEST",
  },
};

export default types;
