import { createStyles } from "@material-ui/core/styles";

const styles = createStyles({
  root: {
    color: "var(--main-black)",
    height: "70vh",
    width: "900px",
    margin: "auto",
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    justifyContent: "flex-start",
    borderRadius: "5px",
    position: "absolute",
    top: "120px",
    left: "calc(50% - 450px)",
  },
  modalHeadingContainer: {
    height: "10em",
    width: "100%",
    display: "flex",
    flexDirection: "column",
  },
  subheading: {
    fontSize: "3rem",
    textAlign: "left",
    fontWeight: '700',
    margin: "30px auto auto 0px",
  },
  infoDivider: {
    display: 'inline-block',
    width: '2px',
    backgroundColor: 'black',
    margin: '0 1rem',
    height: '5rem',
  },
  mainContainer: {
    height: "80%",
    width: "100%",
    display: "flex",
    flexDirection: "column",
  },
  infoBox: {
    width: "100%",
    height: "20%",
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
  },
  smallBox: {
    display: "flex",
    flexDirection: "column",
    justifyContent: "center",
    alignItems: "flex-start",
    width: "50%",
    height: "100%",
    fontSize: "1.5rem",
    padding: "5px",
    fontWeight: "bold",
  },
  divider: {
    display: "inline-block",
    width: "2px",
    backgroundColor: "black",
    margin: "0 10px",
    height: "7.5em",
  },
  graphBoxContainer: {
    display: "flex",
    height: "80%",
    width: "100%",
  },
  graphBox: {
    display: "flex",
    flexDirection: "column",
    height: "80%",
    width: "30%",
    margin: "auto",
    justifyContent: "flex-start",
    alignItems: "start",
  },
  graphType: {
    fontSize: "2rem",
    marginLeft: "16px",
  },
  radio: {
    width: "20px",
    cursor: "pointer",
    margin: "20px auto 20px 20px",
    transform: "scale(2)",
    color: "var(--main-orange)",
  },
  svg: {
    margin: "20px auto",
  },
  description: {
    fontSize: "1.4rem",
    width: "80%",
    margin: "10px auto auto auto",
  },
  btnBar: {
    width: "100%",
    display: "flex",
    justifyContent: "space-between",
    margin: "0px auto 0 0px",
  },
  btnLeft: {
    fontSize: "1.8rem",
    padding: "20px 0px",
    width: "9em",
    borderRadius: "10px",
    fontFamily: "var(--plain-font)",
    backgroundColor: "var(--main-grey)",
  },
  btnRight: {
    fontSize: "1.8rem",
    padding: "20px 0px",
    width: "10em",
    borderRadius: "10px",
    fontFamily: "var(--plain-font)",
    backgroundColor: "var(--main-grey)",
  },
});

export default styles;
